# Generated by Django 5.2.5 on 2025-08-18 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_product_affiliatelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_name", models.CharField(max_length=255)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_phone", models.CharField(max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("card", "Card"), ("bank", "Bank Transfer")],
                        max_length=20,
                    ),
                ),
                (
                    "proof_of_payment",
                    models.ImageField(blank=True, null=True, upload_to="payments/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.product",
                    ),
                ),
            ],
        ),
    ]
