# Generated by Django 5.2.5 on 2025-09-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashoutrequest",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
