# Generated by Django 5.2.5 on 2025-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_cashoutrequest_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="buyer_email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="buyer_name",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
